In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../reference/n1_classified_alchemical_rules_neg.tsv', sep='\t')
df

,Alchemical_rule,output_reactants_num,popularity,route_ids_size,Reference,Target_molecules,composite_rules_size,Composite_rule_sizes,Composite_rules,Source_composite_rows,pseudo_reactions_size,Pseudo_reaction_ids,classification,Matched_default_rule_ids,Matched_default_rules
0,[C;D3:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D3:1]...,2,27,27,"4,44,151,314,322,489,492,744,1051,1077,1148,16...",C=C1[C@@H](OC(C)=O)C[C@H]2[C@H](CN=[N+]=[N-])[...,3,2,[C;D3:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D3:1]...,"n1_t2_composite_rules.tsv:14,n1_t2_composite_r...",25,"p285,p286,p289,p290,p291,p292,p293,p294,p295,p...",negative,859,[C;D3:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D3:1]...
1,[C;D2:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[N;D1-:3...,2,21,21,"231,333,427,1090,1204,1357,1472,1792,2247,2281...","C#CCCCCN=[N+]=[N-],CC(C)(C)OC(=O)COCCOCCOCCOCC...",5,2,[C;D2:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D2:1]...,"n1_t2_composite_rules.tsv:147,n1_t2_composite_...",20,"p372,p373,p374,p375,p376,p377,p378,p379,p380,p...",negative,2219,[C;D2:1]-[C;D2:2]-[N;D2:4]=[N;D2+:5]>>[N;D1-:4...
2,[C;D2:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,2,15,15,"162,980,1027,1390,1583,1942,1973,3507,4071,552...","CC1CCCC(CC(=O)NCC(N)=O)C1,CCC(=NOCc1ccc(C(F)(F...",7,"2,3",[C;D2:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,"n1_t2_composite_rules.tsv:2474,n1_t2_composite...",14,"p650,p651,p652,p653,p654,p655,p657,p658,p5266,...",negative,540,[C;D2:1]-[C;D3:2](=[O;D1:6])-[N;D2:8]-[C;D2:7]...
3,[C;D2:1]-[C;D2:2]=[O;D1:3]>>[C;D2:1]-[C;D3:2](...,1,10,10,"174,378,1274,1380,2072,3782,4912,5256,6247,8819","CC(=O)N[C@@H](CC=O)c1cccc(F)c1,CC(=O)N[C@@H]1C...",2,2,[C;D2:1](-[C;D2:2])=[O;D1:3]>>[C;D2:1](-[C;D2:...,"n1_t2_composite_rules.tsv:56,n1_t2_composite_r...",10,"p737,p738,p739,p740,p741,p742,p743,p744,p2922,...",negative,1293,[C;D2:1]-[C;D2:2]=[O;D1:3]>>[C;D2:1]-[C;D3:2](...
4,[C;D2:1]-[C;D3:2](=[O;D1:3])-[N;D3:4](-[C;D2:5...,2,9,9,"75,148,1014,1183,1428,2174,3161,4977,6354",CC(C)(C)OC(=O)Nc1cc(Cl)ccc1/C=C/C(=O)N1CCN(Cc2...,2,2,[C;D2:1]-[C;D3:2](-[N;D3:3](-[C;D2:4])-[C;D2:5...,"n1_t2_composite_rules.tsv:5162,n1_t2_composite...",9,"p783,p784,p785,p786,p787,p788,p789,p790,p7935",negative,1352,[C;D2:1]-[C;D3:2](=[O;D1:5])-[N;D3:7](-[C;D2:6...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,[C;D3:1]-[O;D2:2]-[C;D2:3]-[C;D1:4]>>[C;D2:3](...,2,1,1,3727,CCCN(CCC)CCCCN(CCC(=O)OCC)Cc1ccc(CN(Cc2ncc[nH]...,1,2,[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D2:5]-[C;D1...,n1_t2_composite_rules.tsv:1500,1,p4296,negative,7512,[O;D2:2](-[C;D3:3])-[C;D2:4]-[C;D1:6]>>[C;D2:4...
60,[C;D4:1]-[C;D2:2]-[N;D1:3]>>[C;D4:1]-[C;D3:2](...,1,1,1,5925,CC(C)(C)OC(=O)C1CC2(CN)CCC1(CN)CC2,1,2,[C;D4:1]-[C;D2:2]-[N;D1:3]>>[C;D4:1]-[C;D2:2]#...,n1_t2_composite_rules.tsv:3886,1,p6666,negative,2896,[C;D4:1]-[C;D2:2]-[N;D1:3]>>[C;D4:1]-[C;D3:2](...
61,[C;D4:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D4:1]...,2,1,1,254,Cc1ccc(C(F)(F)CN=[N+]=[N-])nc1,1,2,[C;D4:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D4:1]...,n1_t2_composite_rules.tsv:3889,1,p6669,negative,12508,[C;D4:1]-[C;D2:2]-[N;D2:4]=[N;D2+:5]>>[C;D4:1]...
62,[C;D4:1]-[C;D2:2]=[O;D1:3]>>[C;D4:1]-[C;D3:2](...,1,1,1,1080,CC(C)(C)OC(=O)N1CC(Cc2ccccc2)C(F)(C=O)C1,1,2,[C;D4:1]-[C;D2:2]=[O;D1:3]>>[C;D4:1]-[C;D2:2]-...,n1_t2_composite_rules.tsv:3905,1,p6685,negative,2798,[C;D4:1]-[C;D2:2]=[O;D1:6]>>[C;D4:1]-[C;D3:2](...
63,[O;D2:1]-[N;D2:2]-[C;D2:3]-[C;D2:4]>>[O;D2:1]-...,2,1,1,2626,CONCCCc1c(Cl)cc(Cl)cc1Cl,1,2,[O;D2:1]-[N;D2:2]-[C;D2:3]-[C;D2:4]>>[O;D2:1]-...,n1_t2_composite_rules.tsv:5012,1,p7785,negative,11432,[O;D2:1]-[N;D2:2]-[C;D2:4]-[C;D2:3]>>[C;D2:3]-...

,Alchemical_rule,popularity,route_ids_size,Reference,Target_molecules,composite_rules_size,Composite_rule_sizes,Composite_rules,Source_composite_rows,pseudo_reactions_size,Pseudo_reaction_ids,Alchemical_cgr,classification,Matched_default_rule_ids,Matched_default_rules
3,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,23,23,"6,543,1168,1257,1571,1706,2142,2398,2839,3268,...",C=CCc1c(C(=O)NCc2c(C(C)CC=C)cc(C)nc2OC)cccc1N(...,2,"2,3",[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,"n1_t2_composite_rules.tsv:0,n1_t3_composite_ru...",18,"p0,p1,p6,p7,p8,p9,p10,p11,p12,p13,p14,p16,p17,...",[O;2>2;]([C;1>1;])[.>-][C;3>3;]([C;3>3;])(=[O;...,negative,125.0,[C;D3:1]-[C;D3:2](=[O;D1:5])-[N;D2:7]-[C;D2:6]...
10,[C;D3:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D3:1]...,20,20,"4,44,151,314,322,489,492,1051,1077,1148,1669,2...",C=C1[C@@H](OC(C)=O)C[C@H]2[C@H](CN=[N+]=[N-])[...,3,2,[C;D3:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D3:1]...,"n1_t2_composite_rules.tsv:10,n1_t2_composite_r...",15,"p168,p169,p172,p173,p175,p176,p177,p178,p179,p...",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][N;2>1;0>-...,negative,859.0,[C;D3:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D3:1]...
27,[C;D3:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...,17,17,"57,325,418,1031,1309,1960,2165,3285,3389,3542,...",CC(C)(C)OC(=O)N1CC(CN2CCC3(CC2)CCN(Cc2ccc(Br)c...,8,2,[C;D2:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,"n1_t2_composite_rules.tsv:199,n1_t2_composite_...",14,"p522,p523,p524,p525,p526,p980,p981,p982,p983,p...",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][N;3>2;]([...,negative,309.0,[C;D3:1]-[C;D2:2]-[N;D3:5](-[C;D2:4])-[C;D2:6]...
44,[C;D3:1]-[O;D2:2]-[C;D2:3]-[C;D2:4]>>[C;D2:3](...,13,13,"95,575,643,714,718,819,1881,2139,2160,3598,448...",CCCOc1nc(Cc2ccc(Cl)cc2)nc2oc(-c3cc(C)c(OCCCBr)...,1,2,[C;D3:1]-[O;D2:2]-[C;D2:3]-[C;D2:4]>>[C;D2:3](...,n1_t2_composite_rules.tsv:8,6,"p144,p147,p151,p152,p154,p155",[C;1>1;][.>-][O;2>2;]([C;3>3;])[->.][C;2>2;]([...,negative,5051.0,[C;D3:1]-[O;D2:2]-[C;D2:5]-[C;D2:6]>>[C;D3:1]-...
61,[C;D3:1]-[C;D2:2]-[O;D2:3]-[C;D3:4]>>[C;D3:1]-...,10,10,"42,294,433,674,1048,1094,1470,2724,5157,7298","COC(=O)C(C)Oc1ccc(COc2ccc(Cl)cc2)cc1,COc1cc(CO...",6,2,[C;D3:1]-[C;D2:2]-[O;D2:3]-[C;D3:4]>>[C;D3:1]-...,"n1_t2_composite_rules.tsv:201,n1_t2_composite_...",8,"p985,p986,p987,p1616,p1618,p5116,p5117,p6071",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][O;2>1;][C...,negative,39.0,[C;D2:1](-[C;D3:3])-[O;D2:4]-[C;D3:5]>>[O;D1:4...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6902,[C;D4:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,1,1,7053,CC(C)(C)OC(=O)N1CCC(Cc2ccc(-c3ccccc3)cc2)(C(=O...,1,2,[C;D4:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,n1_t2_composite_rules.tsv:5549,1,p6601,[O;2>2;]([C;1>1;])[.>-][C;3>3;]([C;4>4;])(=[O;...,negative,4423.0,[C;D4:1]-[C;D3:2](=[O;D1:3])-[N;D2:5]-[C;D2:4]...
6921,[C;D4:1]-[C;D3:2](=[O;D1:3])-[N;D3:4](-[C;D2:5...,1,1,808,CC(C)(Sc1ccc2nc(N)sc2c1)C(=O)N1CCCC1,1,2,[C;D4:1]-[C;D3:2](=[O;D1:3])-[N;D3:4](-[C;D2:5...,n1_t2_composite_rules.tsv:5567,1,p6619,[O;2>2;]([C;2>2;][C])[.>-][C;3>3;]([C;4>4;])(=...,negative,6502.0,[C;D4:1]-[C;D3:2](=[O;D1:6])-[N;D3:7](-[C;D2:8...
6986,[C;D4:1]-[S;D4:2](=[O;D1:3])(=[O;D1:4])-[N;D2:...,1,1,8511,C=CCC1(S(=O)(=O)Nc2ccc(F)c(F)c2Nc2ccc(I)cc2F)CC1,1,2,[C;D4:1]-[S;D4:2](=[O;D1:3])(=[O;D1:4])-[N;D2:...,n1_t2_composite_rules.tsv:5620,1,p6672,[O;1>1;][.>-][S;4>4;]([C;4>4;])(=[O;1>1;])(=[O...,negative,11590.0,[C;D4:1]-[S;D4:2](=[O;D1:4])(=[O;D1:5])-[N;D2:...
7736,[N;D3:1]-[C;D3:2]:1:[C;D2:3]:[C;D3:4](-[C;D1:5...,1,1,9118,COC(=O)[C@@H]1C[C@@H](S(C)(=O)=O)CN1c1cc(C)nn1...,1,2,[N;D3:1]-[C;D3:2]:1:[C;D2:3]:[C;D3:4](-[C;D1:5...,n1_t2_composite_rules.tsv:6383,1,p7360,[O;1>1;][.>=][C;3>3;][:>.]1([N;3>3;])[:>-][C;2...,negative,15560.0,[N;D3:1]-[C;D3:2]:1:[C;D2:3]:[C;D3:4](-[C;D1:5...
8684,[O;D2:1]-[N;D2:2]-[C;D2:3]-[C;D2:4]>>[O;D2:1]-...,1,1,2626,CONCCCc1c(Cl)cc(Cl)cc1Cl,1,2,[O;D2:1]-[N;D2:2]-[C;D2:3]-[C;D2:4]>>[O;D2:1]-...,n1_t2_composite_rules.tsv:7042,1,p7995,[O;1>1;][.>=][C;2>2;]([->.][N;2>1;][O;2>2;])[C...,negative,11432.0,[O;D2:1]-[N;D2:2]-[C;D2:4]-[C;D2:3]>>[C;D2:3]-...

In [ ]:
neg_num = 61

smarts(df.iloc[neg_num]['Alchemical_rule'])